### ISSUE TITLE
Code doesn't use blurRadius parameter

### ISSUE THREAD

**Issue by NQuinn27** [lukabernardi/LBBlurredImage#10]
Line 32 of UIImageView+LBBlurImageView is the offending one

(Pulled from cocoa pods)

Actual:
blurRadius = (blurRadius <= 0) ? : kLBBlurredImageDefaultBlurRadius;
Should be:
blurRadius = (blurRadius <= 0) ? kLBBlurredImageDefaultBlurRadius : blurRadius;

**Comment by MrAppleBR** [comment]
Agreed!

**Comment by zsk425** [comment]
+1

**Comment by kontextbewusst** [comment]
This is still broken in the most recent Cocoapods version 0.2.2!
