### ISSUE TITLE
Unrecognized selector

### ISSUE THREAD

**Issue by maxydon** [lukabernardi/LBBlurredImage#7]
![screen shot 2014-07-05 at 7 49 06 pm](https://cloud.githubusercontent.com/assets/1210321/3487956/2b0a8264-04b8-11e4-86f0-df480fa3a13b.png)
```  [self.blurredImageView setImageToBlur:[UIImage imageNamed:@"wf_bg"] blurRadius:10 completionBlock:nil];```
called in viewDidLoad and blurredImageView is an IBOutlet

**Comment by gotnull** [comment]
Same issue here if I install it via a CocoaPod.

http://stackoverflow.com/questions/28160977/lbblurredimage-nsinvalidargumentexception

**Comment by lukabernardi** [comment]
I just created a test project using CocoaPods and it seems to work fine.

@maxydon Your exception doesn't seems related to the library.
@gotnull Your exception is most likely because the image you're passing is nil and you're violating `NSParameterAssert(image);`

**Comment by juliogc** [comment]
![screen shot 2015-03-28 at 3 08 59 am](https://cloud.githubusercontent.com/assets/2319449/6879985/de21ec2e-d4f7-11e4-909e-16589f51e98c.png)

The code: 
```objective-c
    UIImage *background = [UIImage imageNamed:@"bg"];

    self.blurredImageView = [[UIImageView alloc] init];
    self.blurredImageView.contentMode = UIViewContentModeScaleAspectFill;
    self.blurredImageView.alpha = 0;
    [self.blurredImageView setImageToBlur:background blurRadius:10 completionBlock:nil];
```
I'm getting this stack trace.
I installed via cocoa pods in a going on project and in a new and clean project. In both I'm getting this error
